stages:
  - build
  - test
  - deploy


build docs:
  stage: build
  script:
    - tox -e docs
  tags:
    - gift-adelie
  artifacts:
    paths:
    - doc/


test Linux:
  stage: test
  script:
      - tox
  tags:
    - gift-linux
  coverage: '/^TOTAL.*\s+(\d+\%)$/'


test macOS:
  stage: test
  script:
      - tox
  tags:
    - gift-mac


test Windows:
  stage: test
  script:
      - tox
  tags:
    - gift-win


deploy docs to staging:
  stage: deploy
  script:
    # Note: the group/username directory must already exist on the server before calling this command
    - rsync -avz -e'ssh -v' --numeric-ids --delete doc/build/html/* staging_docs_rsync:GIFT-Surg/ImageSplit 2>&1
  tags:
    - docs-staging
  environment:
    name: staging
    url: http://gift-adelie.cs.ucl.ac.uk/staging/GIFT-Surg/ImageSplit
  only:
    - master
  dependencies:
    - build docs


deploy docs to production:
  stage: deploy
  script:
    # Note: the group/username directory must already exist on the server before calling this command
    - rsync -avz -e'ssh -v' --numeric-ids --delete doc/build/html/* production_docs_rsync:GIFT-Surg/ImageSplit 2>&1
  tags:
    - docs-production
  environment:
    name: production
  only:
    - public
  dependencies:
    - build docs


pip-installer:
  stage: test
  script:
    # remove any previous distribution files
    - rm -rf dist

    # bundle installer
    - python setup.py bdist_wheel

    # get location of wheel
    - export home_dir=$(pwd)
    - export $wheel_path=$(ls $home_dir/dist/*.whl)  # only one file!

    # test the wheel
    - tox -e pip2 -- $wheel_path
    - tox -e pip3 -- $wheel_path

  tags:
    - gift-linux


